<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pratik-Burde" ignored="2" name="FunctionalTest" tests="4" failures="1" timestamp="22 Dec 2022 15:01:45 GMT" time="0.206" errors="0">
  <testcase name="loginByemail" time="0.041" classname="TestNGTutorial.LoginTest"/>
  <testcase name="loginByemail" time="0.003" classname="TestNGTutorial.LoginTest"/>
  <testcase name="loginByemail" time="0.003" classname="TestNGTutorial.LoginTest"/>
  <testcase name="paymentreturnbybank" time="0.006" classname="TestNGTutorial.PaymentReturns">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNGTutorial.PaymentReturns.paymentreturnbybank(PaymentReturns.java:13)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- paymentreturnbybank -->
  <testcase name="loginByFacebook" time="0.0" classname="TestNGTutorial.LoginTest">
    <ignored/>
  </testcase> <!-- loginByFacebook -->
  <testcase name="loginBytwitter" time="0.0" classname="TestNGTutorial.LoginTest">
    <ignored/>
  </testcase> <!-- loginBytwitter -->
</testsuite> <!-- FunctionalTest -->
