<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Pratik-Burde" ignored="0" name="Default test(failed)" tests="1" failures="1" timestamp="03 Jan 2023 07:58:22 GMT" time="0.457" errors="0">
  <testcase name="StandAloneTest2" time="0.424" classname="SeleniumFrameworkDesign.Test.StandAloneTest2">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: StandAloneTest2([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {password=Go0fy108, product=ZARA COAT 3, email=goofy@gmail.com}]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: StandAloneTest2([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.util.HashMap) {password=Go0fy108, product=ZARA COAT 3, email=goofy@gmail.com}]
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- StandAloneTest2 -->
</testsuite> <!-- Default test(failed) -->
